# Generated by Django 4.0.4 on 2022-05-20 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('terminated', models.BooleanField(default=False)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=200)),
                ('user_postal_address', models.CharField(blank=True, max_length=200)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('form_type', models.SmallIntegerField(blank=True, choices=[(0, 'paper'), (1, 'digital')], null=True)),
                ('accepted_terms_datetime', models.DateTimeField(blank=True, null=True)),
                ('signature', models.TextField()),
                ('recording_type', models.SmallIntegerField(blank=True, choices=[(0, 'video'), (1, 'audio')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('duration_in_seconds', models.IntegerField(default=60)),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('directory_name', models.CharField(editable=False, max_length=250, null=True)),
                ('file_name', models.CharField(editable=False, max_length=250, null=True)),
                ('recording_type', models.SmallIntegerField(choices=[(0, 'video'), (1, 'audio')])),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='memoires.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='memoires.question')),
            ],
        ),
    ]
