# Generated by Django 4.0.4 on 2022-05-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0002_contractconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voiceover',
            field=models.FileField(blank=True, upload_to='questions_voiceover'),
        ),
    ]
