# Generated by Django 4.0.4 on 2022-06-01 15:09

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0003_question_voiceover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractconfig',
            name='html_contract',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
