# Generated by Django 4.0.4 on 2022-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0004_alter_contractconfig_html_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_video', models.FileField(blank=True, upload_to='medias')),
                ('closing_picture', models.FileField(blank=True, upload_to='medias')),
                ('recording_base_path', models.FilePathField()),
            ],
        ),
    ]
