# Generated by Django 4.0.4 on 2022-06-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0005_mediaconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaconfig',
            name='closing_picture',
        ),
        migrations.RemoveField(
            model_name='mediaconfig',
            name='opening_video',
        ),
    ]
