# Generated by Django 4.0.4 on 2022-06-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0010_alter_mediaconfig_recording_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconfig',
            name='closing_picture',
            field=models.FileField(blank=True, upload_to='medias'),
        ),
        migrations.AddField(
            model_name='mediaconfig',
            name='opening_video',
            field=models.FileField(blank=True, upload_to='medias'),
        ),
    ]
