# Generated by Django 4.0.4 on 2022-06-10 11:07

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0013_alter_mediaconfig_recording_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconfig',
            name='docx_contract',
            field=models.FileField(blank=True, help_text="Gabarit du contrat de cession des droits (il possède des variables à remplacer en fonction des informations de l'utilisateur. Ce fichier est utilisé pour générer les documents contractuels finaux.", upload_to='', verbose_name='Contrat docx'),
        ),
        migrations.AlterField(
            model_name='contractconfig',
            name='html_contract',
            field=mdeditor.fields.MDTextField(blank=True, help_text="Gabarit du contrat de cession des droits (il possède des variables à remplacer en fonction des informations de l'utilisateur). Vous pouvez le formater. Ce contrat n'est utilisé que pour la partie front-end. Le document enregistré est dans un autre fichier.", verbose_name='Contrat web (en markdown)'),
        ),
        migrations.AlterField(
            model_name='contractconfig',
            name='location',
            field=models.TextField(blank=True, help_text='Indiquez le lieu à afficher dans les contrats', verbose_name='Lieu de captation'),
        ),
        migrations.AlterField(
            model_name='mediaconfig',
            name='closing_picture',
            field=models.FileField(blank=True, help_text="Sélectionnez l'image à afficher à la dernière étape du questionnaire", upload_to='medias', verbose_name='Image de fin (remerciements, sponsors)'),
        ),
        migrations.AlterField(
            model_name='mediaconfig',
            name='opening_video',
            field=models.FileField(blank=True, help_text='Sélectionnez la vidéo à afficher à la première étape du questionnaire. De préférence au format webm.', upload_to='medias', verbose_name='Vidéo de présentation'),
        ),
        migrations.AlterField(
            model_name='mediaconfig',
            name='recording_base_path',
            field=models.FileField(blank=True, help_text="Sélectionnez un fichier (peu importe lequel) dans le dossier où seront stockés les médias enregistrés. Il peut se situer n'importe où.", null=True, upload_to='', verbose_name='Sélection des chemins des témoignages'),
        ),
    ]
