# Generated by Django 4.0.4 on 2022-06-20 10:13

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0014_contractconfig_docx_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='start_delay_in_seconds',
            field=models.IntegerField(default=60, verbose_name="Délais (en secondes) avant le début de l'enregistrement"),
        ),
        migrations.AlterField(
            model_name='question',
            name='duration_in_seconds',
            field=models.IntegerField(default=60, verbose_name="Durée (en seconde) de l'enregistrement"),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(verbose_name='Ordre de la question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=mdeditor.fields.MDTextField(verbose_name='Texte de la question (avec formatage possible)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='voiceover',
            field=models.FileField(blank=True, upload_to='questions_voiceover', verbose_name='Voix off lisant la question'),
        ),
    ]
