# Generated by Django 4.0.4 on 2022-06-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0015_question_start_delay_in_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaconfig',
            name='recording_base_path',
            field=models.CharField(blank=True, help_text="Mettez le nom du dossier où seront stockés les médias enregistrés. Il peut se situer n'importe où. Mais doit exister.", max_length=300, null=True, verbose_name='Sélection des chemins des témoignages'),
        ),
    ]
