# Generated by Django 4.0.4 on 2022-06-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0016_alter_mediaconfig_recording_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaconfig',
            name='background_color',
            field=models.CharField(blank=True, help_text='En hexadécimal, par exemple : #EBEBF4', max_length=10, null=True, verbose_name='Couleur de fond'),
        ),
    ]
