# Generated by Django 4.0.4 on 2022-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0018_answer_is_contract_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='contract_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediaconfig',
            name='seconds_before_idle',
            field=models.IntegerField(default=300, verbose_name='Nombre de secondes avant redémarrage pour inactivité'),
        ),
    ]
