# Generated by Django 4.0.4 on 2022-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0019_answer_contract_path_mediaconfig_seconds_before_idle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractconfig',
            name='html_contract',
            field=models.TextField(blank=True, help_text="Gabarit du contrat de cession des droits (il possède des variables à remplacer en fonction des informations de l'utilisateur). Vous pouvez le formater. Ce contrat n'est utilisé que pour la partie front-end. Le document enregistré est dans un autre fichier.", verbose_name='Contrat web (en markdown)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Texte de la question (avec formatage possible)'),
        ),
    ]
